### ISSUE TITLE
文章类别归属错误❌

### ISSUE THREAD

**Issue by KimYangOfCat** [TJNU-iOS-Club/BlogSrc-Of-TJNU-iOS-Club#36]
问题：
《2020 iOS Club人员变动通知》一文类别归属为 `Activities`，错误。
修正建议：
根据[《贡献文档》](https://github.com/TJNU-iOS-Club/BlogSrc-Of-TJNU-iOS-Club/blob/master/CONTRIBUTING.md)所诉，此文归类为 `Recent Posts` 或许更为合适
期待修改～

**Comment by godjiawen** [comment]
OK了

**Comment by KimYangOfCat** [comment]
OK了，记得完善isuees的label等信息，然后你关闭issues就好了，以后这些都是你来维护了，加油 @godjiawen
